---
title: "Task 2 - map"
author: "Justus v. Samson-Himmelstjerna"
date: "2022-12-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(leaflet)
library(geojsonio)
library(haven)
library(htmlwidgets)
```

```{r upload data}
survey_df <- readRDS("../../survey/meof_usa_survey_df.RDS")
tracking_df <- readRDS("../../tracking/meof_usa_web_df.RDS")
tracking_df_facts <- readRDS(file = "../../tracking/tracking_df_facts.RDS")
```

```{r data}
# change numeriv values to state names
survey_df$inputstate <- 
  case_when(survey_df$inputstate == 1 ~ "Alabama",
            survey_df$inputstate == 2 ~ "Alaska",
            survey_df$inputstate == 4 ~ "Arizona",
            survey_df$inputstate == 5 ~ "Arkansas",
            survey_df$inputstate == 6 ~ "California",
            survey_df$inputstate == 8 ~ "Colorado",
            survey_df$inputstate == 9 ~ "Connecticut",
            survey_df$inputstate == 10 ~ "Delaware",
            survey_df$inputstate == 11 ~ "District of Columbia",
            survey_df$inputstate == 12 ~ "Florida",
            survey_df$inputstate == 13 ~ "Georgia",
            survey_df$inputstate == 15 ~ "Hawaii",
            survey_df$inputstate == 16 ~ "Idaho",
            survey_df$inputstate == 17 ~ "Illinois",
            survey_df$inputstate == 18 ~ "Indiana",
            survey_df$inputstate == 19 ~ "Iowa",
            survey_df$inputstate == 20 ~ "Kansas",
            survey_df$inputstate == 21 ~ "Kentucky",
            survey_df$inputstate == 22 ~ "Louisiana",
            survey_df$inputstate == 23 ~ "Maine",
            survey_df$inputstate == 24 ~ "Maryland",
            survey_df$inputstate == 25 ~ "Massachusetts",
            survey_df$inputstate == 26 ~ "Michigan",
            survey_df$inputstate == 27 ~ "Minnesota",
            survey_df$inputstate == 28 ~ "Mississippi",
            survey_df$inputstate == 29 ~ "Missouri",
            survey_df$inputstate == 30 ~ "Montana",
            survey_df$inputstate == 31 ~ "Nebraska",
            survey_df$inputstate == 32 ~ "Nevada",
            survey_df$inputstate == 33 ~ "New Hampshire",
            survey_df$inputstate == 34 ~ "New Jersey",
            survey_df$inputstate == 35 ~ "New Mexico",
            survey_df$inputstate == 36 ~ "New York",
            survey_df$inputstate == 37 ~ "North Carolina",
            survey_df$inputstate == 38 ~ "North Dakota",
            survey_df$inputstate == 39 ~ "Ohio",
            survey_df$inputstate == 40 ~ "Oklahoma",
            survey_df$inputstate == 41 ~ "Oregon",
            survey_df$inputstate == 42 ~ "Pennsylvania",
            survey_df$inputstate == 44 ~ "Rhode Island",
            survey_df$inputstate == 45 ~ "South Carolina",
            survey_df$inputstate == 46 ~ "South Dakota",
            survey_df$inputstate == 47 ~ "Tennessee",
            survey_df$inputstate == 48 ~ "Texas",
            survey_df$inputstate == 49 ~ "Utah",
            survey_df$inputstate == 50 ~ "Vermont",
            survey_df$inputstate == 51 ~ "Virginia",
            survey_df$inputstate == 53 ~ "Washington",
            survey_df$inputstate == 54 ~ "West Virginia",
            survey_df$inputstate == 55 ~ "Wisconsin",
            survey_df$inputstate == 56 ~ "Wyoming",
            survey_df$inputstate == 60 ~ "American Samoa",
            survey_df$inputstate == 64 ~ "Federated States of Micronesia",
            survey_df$inputstate == 66 ~ "Guam",
            survey_df$inputstate == 68 ~ "Marshall Islands",
            survey_df$inputstate == 69 ~ "Northern Mariana Islands",
            survey_df$inputstate == 70 ~ "Palau",
            survey_df$inputstate == 72 ~ "Puerto Rico",
            survey_df$inputstate == 74 ~ "U.S. Minor Outlying Islands",
            survey_df$inputstate == 78 ~ "Virgin Islands",
            survey_df$inputstate == 81 ~ "Alberta",
            survey_df$inputstate == 82 ~ "British Columbia",
            survey_df$inputstate == 83 ~ "Manitoba",
            survey_df$inputstate == 84 ~ "New Brunswick",
            survey_df$inputstate == 85 ~ "Newfoundland",
            survey_df$inputstate == 86 ~ "Northwest Territories",
            survey_df$inputstate == 87 ~ "Nova Scotia",
            survey_df$inputstate == 88 ~ "Nunavut",
            survey_df$inputstate == 89 ~ "Ontario",
            survey_df$inputstate == 90 ~ "Prince Edward Island",
            survey_df$inputstate == 91 ~ "Quebec",
            survey_df$inputstate == 92 ~ "Saskatchewan",
            survey_df$inputstate == 93 ~ "Yukon Territory")

# Create a new column for State initials
survey_df$state_initials <- map_chr(survey_df$inputstate,
                                        ~state.abb[match(.x, state.name)])

# select relevant columns
tracking_df_only_facts <- tracking_df_facts %>%
  select(personid, fact_check_usage, fact_check_site) %>%
  unique()

# combined survey & tracking data general
tracking_survey_combined_facts <- survey_df %>%
  left_join(., tracking_df_only_facts, 'personid') %>%
  filter(!is.na(fact_check_usage))

# fact checkers
tracking_survey_combined_facts_users <- survey_df %>%
  left_join(., tracking_df_only_facts, 'personid') %>%
  filter(!is.na(fact_check_usage)) %>%
  filter(fact_check_usage == 1)

# not fact checkers
tracking_survey_combined_facts_non <- survey_df %>%
  left_join(., tracking_df_only_facts, 'personid') %>%
  filter(!is.na(fact_check_usage)) %>%
  filter(fact_check_usage == 0)
```

```{r interactive leaflet map}
# Read in geojson data for US states
states <- geojson_read("https://rstudio.github.io/leaflet/json/us-states.geojson", what = "sp")

# Filter the data to only include the relevant columns
tracking_survey_compact <- tracking_survey_combined_facts %>% 
  select(inputstate, fact_check_usage, fact_check_site, pid3)

# Group data by inputstate and pid3 and calculate number of individuals affiliated with each party per state
party_data <- tracking_survey_compact %>%
  group_by(inputstate, pid3) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  # Consider any number that is not affiliated with a party as NA
  mutate(pid3 = ifelse(pid3 %in% c(1, 2, 3), pid3, NA)) %>% 
  group_by(inputstate) %>%
  arrange(desc(count)) %>%  # Sort data by count in descending order
  slice(1) %>% 
  drop_na() # Select first row for each group

# Calculate number of people using fact checking websites and number of people not using these sites for each state
fact_check_data <- tracking_survey_compact %>%
  group_by(inputstate) %>%
  summarize(fact_check_yes = sum(fact_check_usage),
            fact_check_no = n() - sum(fact_check_usage)) %>%
  ungroup()

# Create a new color scale using the colorFactor function
color_scale_1 <- colorFactor(
  palette = c("blue", "red", "yellow"),  # Specify the colors to use
  domain = party_data$pid3  # Use the values of pid3 as the categorical variable
)

# Create leaflet map using tracking_survey_compact data as default data
map <- leaflet(data = tracking_survey_compact) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  # Add states data as a layer
  addPolygons(data = states,
              fillColor = ~color_scale_1(party_data$pid3),  # Use the new color scale
              color = "white", weight = 0.5,
# Add popups displaying number of people using and not using fact checking websites when hovering over a state
              popup = paste(
                "Fact check usage:<br>Yes: ", fact_check_data$fact_check_yes,
                "<br>No: ", fact_check_data$fact_check_no
              )
  ) %>%
  # Add the legend to the map
  addLegend(title = "Majority affiliation to Political Party",
            colors = c("blue", "red", "yellow"),
            labels = c("Democrat", "Republican", "Independent"))
map
```

```{r second map using color scale based on percentage}
# Calculate percentage of people using fact checking websites for each state
fact_check_data <- tracking_survey_compact %>%
  group_by(inputstate) %>%
  summarize(fact_check_yes = sum(fact_check_usage),
            fact_check_no = n() - sum(fact_check_usage)) %>%
  ungroup() %>%
  mutate(percent_fact_check = fact_check_yes / (fact_check_yes + fact_check_no))

# Create color scale based on percentage of people using fact checking websites
color_scale_2 <- colorNumeric(
  palette = "Blues",
  domain = fact_check_data$percent_fact_check
)

# Create leaflet map using tracking_survey_compact data as default data
leaflet(data = tracking_survey_compact) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  # Add states data as a layer
  addPolygons(data = states,
              fillColor = ~color_scale_2(fact_check_data$percent_fact_check),
              color = "white", weight = 0.5,
              # Set opacity based on percentage of people using fact checking websites
              opacity = fact_check_data$percent_fact_check + 0.1,
              # Add popups displaying number of people using and not using fact checking websites when hovering over a state
              popup = paste(
                "Fact check usage:<br>Yes: ", fact_check_data$fact_check_yes,
                "<br>No: ", fact_check_data$fact_check_no
              )
  )
```
```{r}
# Read in geojson data for US states
states <- geojson_read("https://rstudio.github.io/leaflet/json/us-states.geojson", what = "sp")

# Filter the data to only include the relevant columns
tracking_survey_compact <- tracking_survey_combined_facts %>% 
  select(inputstate, fact_check_usage, fact_check_site, pid3)

# Group data by inputstate and pid3 and calculate number of individuals affiliated with each party per state
party_data <- tracking_survey_compact %>%
  group_by(inputstate, pid3) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  # Consider any number that is not affiliated with a party as NA
  mutate(pid3 = ifelse(pid3 %in% c(1, 2, 3), pid3, NA)) %>% 
  group_by(inputstate) %>%
  arrange(desc(count)) %>%  # Sort data by count in descending order
  slice(1) %>% 
  drop_na() # Select first row for each group

# Calculate number of people using fact checking websites and number of people not using these sites for each state
fact_check_data <- tracking_survey_compact %>%
  group_by(inputstate) %>%
  summarize(fact_check_yes = sum(fact_check_usage),
            fact_check_no = n() - sum(fact_check_usage)) %>%
  ungroup() %>%
  mutate(percent_fact_check = fact_check_yes / (fact_check_yes + fact_check_no))

# Create first color scale using the colorFactor function
color_scale_1 <- colorFactor(
  palette = c("blue", "red", "yellow"),  # Specify the colors to use
  domain = party_data$pid3  # Use the values of pid3 as the categorical variable
)

# Create color scale based on percentage of people using fact checking websites
color_scale_2 <- colorNumeric(
  palette = "Blues",
  domain = fact_check_data$percent_fact_check
)

# Create leaflet map using tracking_survey_compact data as default data
final_map <- leaflet(data = tracking_survey_compact) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  # Add states data as a layer
  addPolygons(data = states,
              fillColor = ~color_scale_1(party_data$pid3),  # Use the new color scale
              color = "white", weight = 0.5,
# Add popups displaying number of people using and not using fact checking websites when hovering over a state
              popup = paste(
                "Fact check usage:<br>Yes: ", fact_check_data$fact_check_yes,
                "<br>No: ", fact_check_data$fact_check_no
              ),
              group = "Party Affiliations",
  ) %>% 
  addPolygons(data = states,
              fillColor = ~color_scale_2(fact_check_data$percent_fact_check),
              color = "white", weight = 0.5,
              # Set opacity based on percentage of people using fact checking websites
              opacity = fact_check_data$percent_fact_check,
              # Add popups displaying number of people using and not using fact checking websites when hovering over a state
              popup = paste(
                "Fact check usage:<br>Yes: ", fact_check_data$fact_check_yes,
                "<br>No: ", fact_check_data$fact_check_no
              ),
              group = "Percentage of People using Fact-Checking",
              fillOpacity = .5
  ) %>%
  addLayersControl(
    baseGroups = c("Party Affiliations", "Percentage of People using Fact-Checking"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  # Add the legend to the map
  addLegend(title = "Majority affiliation to Political Party",
            colors = c("blue", "red", "yellow"),
            labels = c("Democrat", "Republican", "Independent"))
final_map
```

```{r}
# Save the map as an HTML file
saveWidget(final_map, file = "map.html")
```